# Generated by Django 5.2.8 on 2026-04-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podmefomcloudapp', '0002_track_rejection_reason_track_status_track_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Трек на модерации',
                'verbose_name_plural': 'Треки на модерации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('podmefomcloudapp.track',),
        ),
        migrations.CreateModel(
            name='TrackRejectedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Отклонённый трек',
                'verbose_name_plural': 'Отклонённые треки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('podmefomcloudapp.track',),
        ),
    ]
